### ISSUE TITLE
Polygon Deployment Discovery

### ISSUE THREAD

**Issue by apbendi** [ScopeLift/umbra-protocol#200] opened 2021-07-20 20:28 UTC
Questions:

* Contract changes required? (probably not)
* Development tools (deployment, network forking, contract verification, testnet)
* How to manage relaying with no ITX (Infura + custom relayer since gas is cheap? Gas price estimation?)
* Fetching event log history
* UX considerations
   * Listing different tokens / default is Matic
   * Show network / network selector

**Comment by mds1** [comment] 2021-07-23 00:49
> Contract changes required? (probably not)

- No contract changes are needed. See the [docs](https://docs.matic.network/docs/develop/hardhat), where they show how to deploy with Hardhat using the ordinary solc compiler
- For deployments, as long as we use the same deployer account + nonce we'll be able to get the same addresses, which is ideal

> Development tools (deployment, network forking, contract verification, testnet)

- Since it's the same as the EVM, this should all behave the same and is backed up by their docs, which show ordinary Hardhat usage
- The hardhat-etherscan plugin seems to support Polygon based on [this portion](https://github.com/nomiclabs/hardhat/blob/d4d9e5e28bcf6c65f2b03bcd765fc7a0da04366c/packages/hardhat-etherscan/src/network/prober.ts#L90-L93) of code
- Testnet is called Polygon Mumbai (parent chain is Goërli) and has a chainId of [80001](https://docs.matic.network/docs/develop/network-details/network)
- [Polygonscan](https://polygonscan.com/) is Etherscan's block explorer for Polygon. There's also a version for the [Mumbai testnet](https://mumbai.polygonscan.com/)
- Pushed a [commit](https://github.com/ScopeLift/umbra-protocol/commit/7a85f4195e631b496472ee26eb4e8ecbac05bb70) to a new `polygon-support` branch, which updates the Hardhat config to support Polygon
    - Chain ID of [137](https://docs.matic.network/docs/develop/network-details/network/)
    - RPC is `https://polygon-mainnet.infura.io/v3/projectId`
- To use Infura, you'll need to add the Polygon PoS add-on to your account. Right now that add-on is free, but I don't know for how long it will be free for. Related announcement [blog post](https://blog.infura.io/polygon-now-available/) 

> How to manage relaying with no ITX (Infura + custom relayer since gas is cheap? Gas price estimation?)

- [MATIC](https://etherscan.io/token/0x7D1AfA7B718fb893dB30A3aBc0Cfc608AaCfeBB0) can be obtained by purchased MATIC on L1 and depositing it to Polygon with https://wallet.matic.network/ ([source](https://docs.matic.network/docs/develop/network-details/gas-token))
- Relayer will have to be updated to just send a normal, non-ITX meta-transaction if the network is Polygon (whether it's a separate endpoint or based on `chainId` in the POST body is TBD and out of scope of this issue)
- Gas estimation: Matic Gas Station can be used to estimate gas prices. API endpoint and more details can be found [here](https://docs.matic.network/docs/develop/tools/matic-gas-station). 
    - There's a UI version here: https://www.polygongasstation.com/ 
    - The gas prices returned from the endpoint seem to be extremely overestimated. As I write this, the fastest speed recommends using 140 gwei, but I sent a transaction for 1.01 gwei (the default price MetaMask suggested) and it confirmed in < 5 seconds
    - MetaMask seems to be using the gas price returned from the `eth_gasPrice` RPC method, as this returned 1.01 gwei in my test
    - Even so, gas prices are so cheap that a 140 gwei transfer is still only $0.0000000495 cents, so we shouldn't worry too much about overestimating for now, but should try to figure out a better way to estimate

> Fetching event log history

Based on all the above, I'm pretty confident this will work the same as it does on L1

> UX considerations
>     - Listing different tokens / default is Matic
>     - Show network / network selector

- The mappings from mainnet token addresses to Polygon token addresses can be found [here](https://docs.matic.network/docs/develop/network-details/mapped-tokens). MATIC, DAI, and USDC are all on that list, so we should be good on token support for now
- We'll have to update a few frontend things to account for different token addresses and use a different token list if connected to Polygon
- Network selector in the top right is a good idea. For some design inspiration, see Uniswap's design below when you are connected to Optimism (this network selector and message only shows up when connected to supported L2s, and not if you connected to mainnet)

![image](https://user-images.githubusercontent.com/17163988/126725884-f03597fe-c7f2-485f-a56f-57c21ce9c947.png)

**Comment by mds1** [comment] 2021-12-10 19:13
Polygon support completed + deployed in https://github.com/ScopeLift/umbra-protocol/pull/251

**Closed by mds1** 2021-12-10 19:13 UTC
Labels: P1
